function generateLargeMosaicInSteps
    mosaicFOV = 10;
    coneSpacingDistribution(mosaicFOV);
    
    visualizationUpdateIterations = 5;
    
    tolerances = 1.5 % [1.2 1.5 2];
    for tolIndex = 1:numel(tolerances)
        mosaicParams = struct(...
            'resamplingFactor', 7, ...
            'fovDegs', mosaicFOV, ...
            'LMSRatio', [0.60 0.30 0.10], ...
            'sConeMinDistanceFactor', 3, ...
            'sConeFreeRadiusMicrons', 45, ...
            'latticeAdjustmentPositionalToleranceF', tolerances(tolIndex), ...
            'latticeAdjustmentDelaunayToleranceF', 1e-3, ...
            'queryGridAdjustmentIterations', 100, ...           % Pass Inf, to avoid querying
            'visualizationUpdateIterations', visualizationUpdateIterations, ...
            'maxGridAdjustmentIterations', 10000, ...
            'marginF',[]....
        );

        theMosaic = coneMosaicHex(mosaicParams.resamplingFactor, ...                     
            'fovDegs',                       mosaicParams.fovDegs, ...                   
            'spatialDensity',                [0 mosaicParams.LMSRatio]', ...
            'sConeMinDistanceFactor',        mosaicParams.sConeMinDistanceFactor, ...
            'sConeFreeRadiusMicrons',        mosaicParams.sConeFreeRadiusMicrons, ... 
            'eccBasedConeDensity',           true, ...                                  % cone density varies with eccentricity
            'eccBasedConeQuantalEfficiency', true, ...                                  % cone quantal efficiency varies with eccentricity
            'latticeAdjustmentPositionalToleranceF',mosaicParams.latticeAdjustmentPositionalToleranceF, ...   
            'latticeAdjustmentDelaunayToleranceF',  mosaicParams.latticeAdjustmentDelaunayToleranceF, ...
            'marginF',                              mosaicParams.marginF, ...
            'queryGridAdjustmentIterations',        mosaicParams.queryGridAdjustmentIterations, ...
            'visualizationUpdateIterations',        mosaicParams.visualizationUpdateIterations, ...
            'maxGridAdjustmentIterations',          mosaicParams.maxGridAdjustmentIterations);

        
        theMosaic.visualizeGrid('ticksInVisualDegs', true);
        mosaicFileName = sprintf('ConeMosaic_%2.1fDegs_PosTolerance%2.6f', mosaicFOV, mosaicParams.latticeAdjustmentPositionalToleranceF);
        
        % Print final figure
        hFig = figure(111);
        NicePlot.exportFigToPDF(sprintf('%s.pdf',mosaicFileName), hFig, 300);
        
        % Save mosaic
        mosaicFileName = sprintf('%s.mat',mosaicFileName);
        save(mosaicFileName, 'theMosaic');
        fprintf('Mosaic saved in ''%s''.\n', mosaicFileName);
    end % tolIndex
    
end