function run_cBanksEtAlPhotocurrentAndEyeMovementsJob()

    emPathType = 'frozen0';     % 'random'; %'frozen0';  % random
    
    classifierSignal = 'isomerizations';
    classifierType = 'mlpt';
    
    ramPercentageEmployed = 1.0;
    
    nTrainingSamples = 32;
    
    responseStabilizationMilliseconds = 100;
    responseExtinctionMilliseconds = 100;   % use 400 for photocurrents computations
    freezeNoise = false;
      
    computeMosaic = false;
    computeResponses = true;
    visualizeResponses = true;
    visualizeSpatialScheme = true;
    
    cyclesPerDegreeExamined = [20];
    luminancesExamined = [34];
    nContrastsPerDirection = 12;
    
    if (computeResponses) || (visualizeResponses) 
        c_BanksEtAlPhotocurrentAndEyeMovements(...
            'cyclesPerDegree', cyclesPerDegreeExamined, ...
            'luminances', luminancesExamined, ...
            'nTrainingSamples', nTrainingSamples, ...
            'nContrastsPerDirection', 12, ...
            'ramPercentageEmployed', ramPercentageEmployed, ...
            'emPathType', emPathType, ...
            'responseStabilizationMilliseconds', responseStabilizationMilliseconds, ...
            'responseExtinctionMilliseconds', responseExtinctionMilliseconds, ...
            'freezeNoise', freezeNoise, ...
            'computeMosaic',computeMosaic, ...
            'computeResponses', computeResponses, ...
            'visualizeResponses', visualizeResponses, ...
            'visualizeSpatialScheme', visualizeSpatialScheme, ...
            'findPerformance', false, ...
            'visualizePerformance', false ...
        );
    end
    
end

