function run_BanksPhotocurrentEyeMovementConditions(params)
 
    if (params.deleteResponseInstances)
        c_BanksEtAlPhotocurrentAndEyeMovements(...
            'opticsModel', params.opticsModel, ...
            'blur', params.blur, ...
            'apertureBlur', params.apertureBlur, ...
            'imagePixels', params.imagePixels, ...
            'cyclesPerDegree', params.cyclesPerDegreeExamined, ...
            'luminances', params.luminancesExamined, ...
            'nTrainingSamples', params.nTrainingSamples, ...
            'lowContrast', params.lowContrast, ...
            'highContrast', params.highContrast, ...
            'nContrastsPerDirection', params.nContrastsPerDirection, ...
            'ramPercentageEmployed', params.ramPercentageEmployed, ...
            'emPathType', params.emPathType, ...
            'centeredEMPaths', params.centeredEMPaths, ...
            'responseStabilizationMilliseconds', params.responseStabilizationMilliseconds, ...
            'responseExtinctionMilliseconds', params.responseExtinctionMilliseconds, ...
            'freezeNoise', params.freezeNoise, ...
            'integrationTime', params.integrationTimeMilliseconds/1000, ...
            'coneSpacingMicrons', params.coneSpacingMicrons, ...
            'innerSegmentSizeMicrons', sizeForSquareApertureFromDiameterForCircularAperture(params.innerSegmentDiameter), ...
            'conePacking', params.conePacking, ...
            'LMSRatio', params.LMSRatio, ...
            'mosaicRotationDegs', params.mosaicRotationDegs, ...
            'computeMosaic', false, ...
            'visualizeMosaic', false, ...
            'computeResponses', false, ...
            'computePhotocurrentResponseInstances', false, ...
            'visualizeResponses', false, ...
            'visualizeSpatialScheme', false, ...
            'findPerformance', false, ...
            'visualizePerformance', false, ...
            'deleteResponseInstances', true);
        return;
    end
    
    if (params.computeResponses) || (params.visualizeResponses) || (params.visualizeMosaic)
        c_BanksEtAlPhotocurrentAndEyeMovements(...
            'opticsModel', params.opticsModel, ...
            'blur', params.blur, ...
            'apertureBlur', params.apertureBlur, ...
            'imagePixels', params.imagePixels, ...
            'cyclesPerDegree', params.cyclesPerDegreeExamined, ...
            'luminances', params.luminancesExamined, ...
            'nTrainingSamples', params.nTrainingSamples, ...
            'lowContrast', params.lowContrast, ...
            'highContrast', params.highContrast, ...
            'nContrastsPerDirection', params.nContrastsPerDirection, ...
            'ramPercentageEmployed', params.ramPercentageEmployed, ...
            'emPathType', params.emPathType, ...
            'centeredEMPaths', params.centeredEMPaths, ...
            'responseStabilizationMilliseconds', params.responseStabilizationMilliseconds, ...
            'responseExtinctionMilliseconds', params.responseExtinctionMilliseconds, ...
            'freezeNoise', params.freezeNoise, ...
            'integrationTime', params.integrationTimeMilliseconds/1000, ...
            'coneSpacingMicrons', params.coneSpacingMicrons, ...
            'innerSegmentSizeMicrons', sizeForSquareApertureFromDiameterForCircularAperture(params.innerSegmentDiameter), ...
            'conePacking', params.conePacking, ...
            'LMSRatio', params.LMSRatio, ...
            'mosaicRotationDegs', params.mosaicRotationDegs, ...
            'computeMosaic', params.computeMosaic, ...
            'visualizeMosaic', params.visualizeMosaic, ...
            'computeResponses', params.computeResponses, ...
            'computePhotocurrentResponseInstances', params.computePhotocurrentResponseInstances, ...
            'visualizeResponses', params.visualizeResponses, ...
            'visualizeSpatialScheme', params.visualizeSpatialScheme, ...
            'findPerformance', false, ...
            'visualizePerformance', false, ...
            'performanceSignal' , params.performanceSignal, ...
            'performanceClassifier', params.performanceClassifier ...
        );
    end
    
    if (params.findPerformance) || (params.visualizePerformance)
            perfData = c_BanksEtAlPhotocurrentAndEyeMovements(...
                'opticsModel', params.opticsModel, ...
                'blur', params.blur, ...
                'apertureBlur', params.apertureBlur, ...
                'imagePixels', params.imagePixels, ...
                'cyclesPerDegree', params.cyclesPerDegreeExamined, ...
                'luminances', params.luminancesExamined, ...
                'nTrainingSamples', params.nTrainingSamples, ...
                'nContrastsPerDirection', params.nContrastsPerDirection, ...
                'lowContrast', params.lowContrast, ...
                'highContrast', params.highContrast, ...
                'ramPercentageEmployed', params.ramPercentageEmployed, ...
                'emPathType', params.emPathType, ...
                'centeredEMPaths', params.centeredEMPaths, ...
                'responseStabilizationMilliseconds', params.responseStabilizationMilliseconds, ...
                'responseExtinctionMilliseconds', params.responseExtinctionMilliseconds, ...
                'freezeNoise', params.freezeNoise, ...
                'integrationTime', params.integrationTimeMilliseconds/1000, ...
                'coneSpacingMicrons', params.coneSpacingMicrons, ...
                'innerSegmentSizeMicrons', sizeForSquareApertureFromDiameterForCircularAperture(params.innerSegmentDiameter), ...
                'conePacking', params.conePacking, ...
                'LMSRatio', params.LMSRatio, ...
                'mosaicRotationDegs', params.mosaicRotationDegs, ...
                'computeMosaic', false, ...
                'visualizeMosaic', false, ...
                'computeResponses', false, ...
                'visualizeResponses', false, ...
                'visualizeSpatialScheme', params.visualizeSpatialScheme, ...
                'findPerformance', params.findPerformance, ...
                'visualizePerformance', params.visualizePerformance, ...
                'visualizeKernelTransformedSignals', params.visualizeKernelTransformedSignals, ...
                'parforWorkersNumForClassification', 4, ...
                'performanceSignal' , params.performanceSignal, ...
                'performanceClassifier', params.performanceClassifier, ...
                'performanceTrialsUsed', params.nTrainingSamples ...
                );
            thresholds = perfData.mlptThresholds.thresholdContrasts
    end
end

