function run_cBanksEtAlPhotocurrentAndEyeMovementsJob()

    mosaicType = 'originalBanks';
    
    switch mosaicType
        case 'originalBanks'
            % 1. Original Banks et al mosaic params
            coneSpacingMicrons = 3.0;
            innerSegmentDiameter = 3.0;    % for a circular sensor
            conePacking = 'hexReg';
            
        case 'defaultIsetbio'
            % 2. Default isetbio mosaic params
            coneSpacingMicrons = 2.0;
            innerSegmentDiameter = 1.5797; % for a circular sensor; this corresponds to the 1.4 micron square pixel 
            conePacking = 'hexReg';
    
        case 'fullIsetbio'
            % 3. spatially-varying density isetbio mosaic params
            coneSpacingMicrons = 2.0;
            innerSegmentDiameter = 1.5797; % for a circular sensor; this corresponds to the 1.4 micron square pixel 
            conePacking = 'hex';
    end
    
    emPathType = 'frozen0';     % 'random'; %'frozen0';  % random
    freezeNoise = ~true;
    nTrainingSamples = 256;
    cyclesPerDegreeExamined =  [10 20 40];
    luminancesExamined =  [34];
    nContrastsPerDirection =  12;
    lowContrast = 0.001;
    highContrast = 0.3;
    
    
    classifierSignal = 'isomerizations';
    classifierType = 'mlpt';
    
    ramPercentageEmployed = 1.0;
    
    % For 5 milliseconds simulation
    responseStabilizationMilliseconds = 20;
    responseExtinctionMilliseconds = 20;   % use 400 for photocurrents computations
    integrationTimeMilliseconds =  5;
    
    % For 100 ms simulation
    responseStabilizationMilliseconds = 0;
    responseExtinctionMilliseconds = 100;   % use 400 for photocurrents computations
    integrationTimeMilliseconds =  100;
    
   
    
    computeMosaic = true;
    computeResponses = true;
    visualizeResponses = true;
    visualizeSpatialScheme = true;
    findPerformance = true;
    visualizePerformance = true;
    
    
    if (computeResponses) || (visualizeResponses) || (visualizeSpatialScheme) 
        c_BanksEtAlPhotocurrentAndEyeMovements(...
            'cyclesPerDegree', cyclesPerDegreeExamined, ...
            'luminances', luminancesExamined, ...
            'nTrainingSamples', nTrainingSamples, ...
            'lowContrast', lowContrast, ...
            'highContrast', highContrast, ...
            'nContrastsPerDirection', nContrastsPerDirection, ...
            'ramPercentageEmployed', ramPercentageEmployed, ...
            'emPathType', emPathType, ...
            'responseStabilizationMilliseconds', responseStabilizationMilliseconds, ...
            'responseExtinctionMilliseconds', responseExtinctionMilliseconds, ...
            'freezeNoise', freezeNoise, ...
            'integrationTime', integrationTimeMilliseconds/1000, ...
            'coneSpacingMicrons', coneSpacingMicrons, ...
            'innerSegmentSizeMicrons', sizeForSquareApertureFromDiameterForCircularAperture(innerSegmentDiameter), ...
            'conePacking', conePacking, ...
            'computeMosaic',computeMosaic, ...
            'computeResponses', computeResponses, ...
            'visualizeResponses', visualizeResponses, ...
            'visualizeSpatialScheme', visualizeSpatialScheme, ...
            'findPerformance', false, ...
            'visualizePerformance', false ...
        );
    end
    
    if (findPerformance) || (visualizePerformance) 
        c_BanksEtAlPhotocurrentAndEyeMovements(...
            'cyclesPerDegree', cyclesPerDegreeExamined, ...
            'luminances', luminancesExamined, ...
            'nTrainingSamples', nTrainingSamples, ...
            'nContrastsPerDirection', nContrastsPerDirection, ...
            'lowContrast', lowContrast, ...
            'highContrast', highContrast, ...
            'ramPercentageEmployed', ramPercentageEmployed, ...
            'emPathType', emPathType, ...
            'responseStabilizationMilliseconds', responseStabilizationMilliseconds, ...
            'responseExtinctionMilliseconds', responseExtinctionMilliseconds, ...
            'freezeNoise', freezeNoise, ...
            'integrationTime', integrationTimeMilliseconds/1000, ...
            'coneSpacingMicrons', coneSpacingMicrons, ...
            'innerSegmentSizeMicrons', sizeForSquareApertureFromDiameterForCircularAperture(innerSegmentDiameter), ...
            'conePacking', conePacking, ...
            'computeMosaic', false, ...
            'computeResponses', false, ...
            'visualizeResponses', false, ...
            'visualizeSpatialScheme', visualizeSpatialScheme, ...
            'findPerformance', findPerformance, ...
            'visualizePerformance', visualizePerformance ...
        );
    end
    
    
end

