function run_c_DavilaGeislerReplicateEyeMovementsJob
    % What to do ?
    computeMosaic = ~true;
    visualizeMosaic = ~true;
    computeResponses = ~true;
    visualizeResponses = ~true;
    visualizeSpatialScheme = true;
    findPerformance = true;
   
    visualizePerformance = true;
    visualizeTransformedSignals = true;
    
    nTrainingSamples = 128;
    spotAreaMinutes = [10^-0.25 logspace(0.1, 2,8) 10^2.5]
    spotDiametersMinutes = fliplr(spotDiameterFromArea(spotAreaMinutes));
    %spotDiametersMicrons = spotDiametersMinutes/60*300
    
    nContrastsPerDirection = 10;
    highContrast = 0.01;
    lowContrast = 0.0001;
    backgroundSizeDegs = 1.2;  % 0.1, 0.15, 0.3 works
    
    blur = false;           % NO OPTICS
    emPathType = 'frozen0'; % 'frozen0'; %random'; %'random';
    conePacking = 'hex';
    LMSRatio = [0.62 0.31 0.07];
    realisticSconeSubmosaic = true;
    
    responseStabilizationMilliseconds = 20;
    responseExtinctionMilliseconds = 50;

    thresholdSignal = 'isomerizations';
    thresholdMethod = 'svmGaussianRF'; %'svmGaussianRF'; %'svm'; %'mlpt'%
    useRBFSVMKernel = false;
    
    % Spatial pooling kernel parameters
    spatialPoolingKernelParams.type = 'GaussianRF';
    spatialPoolingKernelParams.activationFunction = 'linear';  % Choose between 'energy' and 'fullWaveRectifier'
    spatialPoolingKernelParams.adjustForConeDensity = false;
    spatialPoolingKernelParams.temporalPCAcoeffs = Inf;  % Inf, results in no PCA, just the raw time series
    spatialPoolingKernelParams.shrinkageFactor = 4.0;  % > 1, results in expansion, < 1 results in shrinking
    
    if (computeResponses) || (visualizeResponses) || (visualizeSpatialScheme) || (visualizeMosaic)
        c_DavilaGeislerReplicateEyeMovements(...
            'nTrainingSamples', nTrainingSamples, ...
            'backgroundSizeDegs', backgroundSizeDegs, ...
            'spotDiametersMinutes', spotDiametersMinutes, ...
            'imagePixels', 1000, ...
            'blur', blur, ...
            'highContrast', highContrast, ...
            'lowContrast', lowContrast, ...
            'nContrastsPerDirection', nContrastsPerDirection, ...
            'conePacking', conePacking, ...
            'LMSRatio', LMSRatio, ...
            'realisticSconeSubmosaic', realisticSconeSubmosaic, ...
            'computeMosaic', computeMosaic, ...
            'computeResponses', computeResponses, ...
            'emPathType', emPathType, ...
            'responseStabilizationMilliseconds', responseStabilizationMilliseconds, ...
            'responseExtinctionMilliseconds', responseExtinctionMilliseconds, ...
            'visualizeMosaic', visualizeMosaic, ...
            'visualizeResponses', visualizeResponses, ...
            'visualizeSpatialScheme', visualizeSpatialScheme, ...
            'visualizeTransformedSignals', visualizeTransformedSignals, ...
            'findPerformance', false, ...
            'fitPsychometric', false, ...
            'visualizePerformance', false, ...
            'thresholdCriterionFraction', 0.701, ...
            'thresholdSignal' , thresholdSignal, ...
            'thresholdMethod', thresholdMethod ...
        );
    end
    
    
    if (findPerformance) || (visualizePerformance)
        c_DavilaGeislerReplicateEyeMovements(...
            'nTrainingSamples', nTrainingSamples, ...
            'backgroundSizeDegs', backgroundSizeDegs, ...
            'spotDiametersMinutes', spotDiametersMinutes, ...
            'imagePixels', 1000, ...
            'blur', blur, ...
            'highContrast', highContrast, ...
            'lowContrast', lowContrast, ...
            'nContrastsPerDirection', nContrastsPerDirection, ...
            'conePacking', conePacking, ...
            'LMSRatio', LMSRatio, ...
            'realisticSconeSubmosaic', realisticSconeSubmosaic, ...
            'computeMosaic', false, ...
            'computeResponses', false, ...
            'emPathType', emPathType, ...
            'responseStabilizationMilliseconds', responseStabilizationMilliseconds, ...
            'responseExtinctionMilliseconds', responseExtinctionMilliseconds, ...
            'visualizeMosaic', false, ...
            'visualizeResponses', visualizeResponses, ...
            'visualizeSpatialScheme', visualizeSpatialScheme, ...
            'visualizeTransformedSignals', visualizeTransformedSignals, ...
            'findPerformance', findPerformance, ...
            'fitPsychometric', true, ...
            'visualizePerformance', visualizePerformance, ...
            'thresholdSignal' , thresholdSignal, ...
            'thresholdMethod', thresholdMethod, ...
            'useRBFSVMKernel', useRBFSVMKernel, ...
            'spatialPoolingKernelParams', spatialPoolingKernelParams ...
        );
    end
end

function diameter = spotDiameterFromArea(area)
    diameter = 2.0*sqrt(area/pi);
end

