function run_c_DavilaGeislerReplicateEyeMovementsJob

    % What to do ?
    computeMosaic = ~true;
    visualizeMosaic = true;
    computeResponses = true;
    visualizeResponses = true;
    visualizeSpatialScheme = ~true;
    findPerformance = ~true;
    fitPsychometric = ~true;
    visualizePerformance = ~true;
    visualizeTransformedSignals = ~true;
    
    nTrainingSamples = 100;
    spotDiametersMinutes = [40];
    nContrastsPerDirection = 15;
    backgroundSizeDegs = 1.0;
    
    responseStabilizationMilliseconds = 50;
    responseExtinctionMilliseconds = 50;
    
    thresholdSignal = 'isomerizations';
    thresholdMethod = 'mlpt'; % 'mlpt';
    
    c_DavilaGeislerReplicateEyeMovements(...
        'nTrainingSamples', nTrainingSamples, ...
        'backgroundSizeDegs', backgroundSizeDegs, ...
        'spotDiametersMinutes', spotDiametersMinutes, ...
        'nContrastsPerDirection', nContrastsPerDirection, ...
        'computeMosaic', computeMosaic, ...
        'computeResponses', computeResponses, ...
        'responseStabilizationMilliseconds', responseStabilizationMilliseconds, ...
        'responseExtinctionMilliseconds', responseExtinctionMilliseconds, ...
        'visualizeMosaic', visualizeMosaic, ...
        'visualizeResponses', visualizeResponses, ...
        'visualizeSpatialScheme', visualizeSpatialScheme, ...
        'visualizeTransformedSignals', visualizeTransformedSignals, ...
        'findPerformance', findPerformance, ...
        'fitPsychometric', fitPsychometric, ...
        'visualizePerformance', visualizePerformance, ...
        'thresholdSignal' , thresholdSignal, ...
        'thresholdMethod', thresholdMethod ...
    );
    


end

