function runTVIcurveJob()

    close all;
    % Set 1
    nTrainingSamples = 128;
    lowContrast = 1e-4;
    highContrast = 0.1;
    fieldOfViewDegs = 0.8;
    testDiameterDegs = 0.4;
    
    % Set 2
    nTrainingSamples = 256;
    lowContrast =  3e-4;
    highContrast = 0.3;
    fieldOfViewDegs = 1.0;
    testDiameterDegs = 0.5;
    
    % Set 3
%     nTrainingSamples = 32;
%     lowContrast =  3e-4;
%     highContrast = 0.3;
%     fieldOfViewDegs = 1.0;
%     testDiameterDegs = 0.5;
    
    computeResponses = false;
    findPerformance = ~true;
    visualizePerformance = true;
    
    if (computeResponses)
        c_TVIcurve('computeMosaic',false, ...
            'nTrainingSamples', nTrainingSamples, ...
            'lowContrast', lowContrast, ...
            'highContrast', highContrast, ...
            'fieldOfViewDegs', fieldOfViewDegs, ...
            'testDiameterDegs', testDiameterDegs, ...
            'visualizeSpatialScheme', true, ...
            'findPerformance', false ...
            );
    end
    
    if (findPerformance) || (visualizePerformance)
        c_TVIcurve( 'nTrainingSamples', nTrainingSamples, ...
                'lowContrast', lowContrast, ...
                'highContrast', highContrast, ...
                'fieldOfViewDegs', fieldOfViewDegs, ...
                'testDiameterDegs', testDiameterDegs, ...
                'computeResponses', false, ...
                'visualizeSpatialScheme', false, ...
                'visualizeTransformedSignals', true, ...
                'findPerformance', findPerformance, ...
                'visualizePerformance', visualizePerformance, ...
                'performanceSignal', 'isomerizations', ... % 'isomerizations', ... % 'photocurrents', ...
                'performanceClassifier', 'svmGaussianRF', ... % 'mlpt', 'svmGaussianRF', ...
                'visualizeResponses', false);
    end
    
end

