function dirname = paramsToResponseGenerationDirName(obj,rparams)
% pdirname = paramsToResponseGenerationDirName(obj,rparams)
% 
% Generate a directory names that captures the basic non-color stimulus
% parameters, as well as the oi and mosaic parameters used to generate the responses

if (~strcmp(rparams.type,'ResponseGeneration'))
    error('Incorrect parameter type passed');
end

theGaborName = sprintf('cpd%0.0f_sfv%0.2f_fw%0.3f',...
    rparams.gaborParams.cyclesPerDegree,...
    rparams.gaborParams.fieldOfViewDegs,...
    rparams.gaborParams.gaussianFWHMDegs);

if (~isfield(rparams.temporalParams,'eyesDoNotMove'))
    rparams.temporalParams.eyesDoNotMove = true;
end
theTemporalName = sprintf('tau%0.3f_dur%0.3f_step%0.3f_nem%0.0f_use%0.0f_off%0.0f',...
    rparams.temporalParams.windowTauInSeconds, ...
    rparams.temporalParams.stimulusDurationInSeconds, ...
    rparams.temporalParams.simulationTimeStepSecs, ...
    rparams.temporalParams.eyesDoNotMove, ...
    rparams.temporalParams.secondsToInclude, ...
    rparams.temporalParams.secondsToIncludeOffset);

theOIName = sprintf('b%0.0f_l%0.0f', ...
    rparams.oiParams.blur, ...
    rparams.oiParams.lens);

theMosaicName = sprintf('LMS%0.2f_%0.2f_%0.2f_mfv%0.2f',...
    rparams.mosaicParams.LMSRatio(1),rparams.mosaicParams.LMSRatio(2),rparams.mosaicParams.LMSRatio(3), ...
    rparams.mosaicParams.fieldOfViewDegs);

dirname = [theGaborName '_' theTemporalName '_' theOIName '_' theMosaicName];
