function dirname = paramsToResponseGenerationDirName(obj,params)
% pdirname = paramsToResponseGenerationDirName(obj,params)
% 
% Generate a directory names that captures the basic LMPlane instance generation
% parameters.

if (~strcmp(params.type,'LMPlaneInstance'))
    error('Incorrect parameter type passed');
end

theLMPlaneInstanceName = sprintf('LMPlane_%0.0f_%0.0f_%0.0f_con%0.0f_%0.5f_%0.3f_nt%0.0f',...
    params.startAngle,...
    params.deltaAngle,...
    params.nAngles,...
    params.nContrastsPerDirection, ...
    params.lowContrast, ...
    params.highContrast, ...
    params.trialsNum ...
    );

dirname = theLMPlaneInstanceName;

