function dirname = paramsToColorModulationDirName(obj,params)
% dirname = paramsToColorModulationDirName(obj,params)
%
% Generate a directory names that captures the color stimulus
% parameters

if (~strcmp(params.type,'ColorModulation'))
    error('Incorrect parameter type passed');
end

switch (params.modulationType)
    case 'monitor'
        dirname = sprintf('[CONE_MODULATION]_L%0.0f_M%0.0f_S%0.0f_con%0.5f_wls_%d_%d_%d',...
            100*params.coneContrasts(1),...
            100*params.coneContrasts(2),...
            100*params.coneContrasts(3),...
            100*params.contrast,...
            params.startWl,...
            params.deltaWl,...
            params.endWl);
    case 'AO'
        dirname = sprintf('[SPOT_MODULATION]_%d_%0.1f_con%0.5f_wls_%d_%d_%d',params.spotWavelengthNm,params.spotCornealPowerUW,100*params.contrast,...
            params.startWl,...
            params.deltaWl,...
            params.endWl);
    otherwise
        error('Unknown background type specified');
end





