function dirname = paramsToResponseGenerationDirName(obj,params)
% dirname = paramsToResponseGenerationDirName(obj,params)
%
% Generate a directory names that captures the basic parameters used to
% find threshold.

if (~strcmp(params.type,'threshold'))
    error('Incorrect parameter type passed');
end


switch (params.method)
    case 'svm'
        theThresholdName = sprintf('%s_%s_%dInt_kFold%d_PCA%d_std%d_c%0.2f',...
            params.method, ...
            params.signalSource, ...
            params.nIntervals, ...
            params.kFold, ...
            params.PCAComponents, ...
            params.STANDARDIZE, ...
            params.criterionFraction ...
            );
        
    case 'svmSpaceTimeSeparable'
        if (isfield(params, 'useRBFKernel')) && (params.useRBFKernel)
            methodName = sprintf('%sRBF', params.method);
        else
            methodName = sprintf('%s', params.method);
        end
        theThresholdName = sprintf('%s_%s_%dInt_kFold%d_PCA%d_std%d_c%0.2f',...
            methodName, ...
            params.signalSource, ...
            params.nIntervals, ...
            params.kFold, ...
            params.PCAComponents, ...
            params.standardizeSVMpredictors, ...
            params.criterionFraction ...
            );
        
    case {'svmV1FilterBank', 'svmV1FilterEnsemble', 'svmGaussianRF'}
        if (isfield(params, 'useRBFKernel')) && (params.useRBFKernel)
            methodName = sprintf('%sRBF', params.method);
        else
            methodName = sprintf('%s', params.method);
        end
        
        if (strcmp(params.method,'svmV1FilterEnsemble'))
            methodName = sprintf('%s_%s_%s_pos_%d_bw_%d_dBw_%2.2f_ori_%d_dO_%d', methodName, ...
                params.spatialPoolingKernelParams.type, ...
                params.spatialPoolingKernelParams.activationFunction,...
                params.spatialPoolingKernelParams.shrinkageFactor, ...
                params.spatialPoolingKernelParams.spatialPositionsNum, ...
                numel(params.spatialPoolingKernelParams.cyclesPerRFs), ...
                params.spatialPoolingKernelParams.cyclesPerRFs(2)-params.spatialPoolingKernelParams.cyclesPerRFs(1), ...
                numel(params.spatialPoolingKernelParams.orientations), ...
                params.spatialPoolingKernelParams.orientations(2)-params.spatialPoolingKernelParams.orientations(1) ...
           );
        else
            methodName = sprintf('%s_%s_%s_%0.4fshrinkFactor', methodName, ...
                params.spatialPoolingKernelParams.type, ...
                params.spatialPoolingKernelParams.activationFunction,...
                params.spatialPoolingKernelParams.shrinkageFactor);

        end
        
        theThresholdName = sprintf('%s_%s_%dInt_kFold%d_stdSVMpredictors%d_c%0.2f',...
                methodName, ...
                params.signalSource, ...
                params.nIntervals, ...
                params.kFold, ...
                params.standardizeSVMpredictors, ...
                params.criterionFraction ...
            );
     
    case {'mlpe', 'mlpt'}
        theThresholdName = sprintf('%s_%s_%dInt_kFold%d_c%0.2f',...
            params.method, ...
            params.signalSource, ...
            params.nIntervals, ...
            params.kFold, ...
            params.criterionFraction ... 
        );
    
    case 'mlptGaussianRF'
        if (isfield(params, 'useRBFKernel')) && (params.useRBFKernel)
            methodName = sprintf('%sRBF', params.method);
        else
            methodName = sprintf('%s', params.method);
        end
        
        methodName = sprintf('%s_%s_%s_%0.4fshrinkFactor', methodName, ...
            params.spatialPoolingKernelParams.type, ...
            params.spatialPoolingKernelParams.activationFunction,...
            params.spatialPoolingKernelParams.shrinkageFactor);
        
        theThresholdName = sprintf('%s_%s_%dInt_kFold%d_c%0.2f',...
            methodName, ...
            params.signalSource, ...
            params.nIntervals, ...
            params.kFold, ...
            params.criterionFraction ... 
        );
    
    otherwise
        error('Unknown classification method');
end

if (isfield(params, 'trialsUsed'))
    theThresholdName = sprintf('%s_trialsUsed%d',theThresholdName, params.trialsUsed);
end

if (~isempty(params.evidenceIntegrationTime))
    theThresholdName = sprintf('%s_evidenceIntegrationTimeMilliSecs%2.1f',theThresholdName, params.actualEvidenceIntegrationTime);
end

dirname = theThresholdName;

