function visualizeSceneAndOpticalImage(modulatedScene, oiModulated, paramsList)

    sceneRGB = sceneGet(modulatedScene, 'rgb image');
    sceneSpatialSupport = sceneGet(modulatedScene, 'spatial support');
    xSupport = squeeze(sceneSpatialSupport(1,:,1));
    ySupport = squeeze(sceneSpatialSupport(:,1,2));
    
    opticalImageRGB = oiGet(oiModulated, 'rgb image');
    oiSpatialSupport = oiGet(oiModulated, 'spatial support');
    oiXSupport = squeeze(oiSpatialSupport(1,:,1));
    oiYSupport = squeeze(oiSpatialSupport(:,1,2));
    
    % Draw
    subplotPosVectors = NicePlot.getSubPlotPosVectors(...
           'rowsNum', 2, ...
           'colsNum', 1, ...
           'heightMargin',   0.04, ...
           'widthMargin',    0.01, ...
           'leftMargin',     0.01, ...
           'rightMargin',    0.006, ...
           'bottomMargin',   0.02, ...
           'topMargin',      0.02);
      
    hFig = figure(99); clf;
    formatFigureForPaper(hFig, 'figureType', 'STIMULUS_AND_OPTICAL_IMAGE');
    
    ax = subplot('Position', subplotPosVectors(1,1).v);
    image(ax, xSupport, ySupport, sceneRGB);
    t = 'scene';
    formatFigureForPaper(hFig, ...
            'figureType', 'STIMULUS_AND_OPTICAL_IMAGE', ...
            'theAxes', ax, ...
            'theText', t, ...
            'theTextFontSize', [], ...
            'theFigureTitle', '');
        
    ax = subplot('Position', subplotPosVectors(2,1).v);
    image(ax, oiXSupport, oiYSupport, opticalImageRGB);
    t = 'optical image';
    formatFigureForPaper(hFig, ...
            'figureType', 'STIMULUS_AND_OPTICAL_IMAGE', ...
            'theAxes', ax, ...
            'theText', t, ...
            'theTextFontSize', [], ...
            'theFigureTitle', '');
    
    drawnow;
    
    if (~isempty(paramsList))
        % Export to PDF
        theProgram = mfilename;
        rwObject = IBIOColorDetectReadWriteBasic;
        data = 0;
        fileName = sprintf('SceneRGBandOpticalImageRGB');
        rwObject.write(fileName, data, paramsList, theProgram, ...
               'type', 'NicePlotExportPDF', 'FigureHandle', hFig, 'FigureType', 'pdf');
    end
    
end

