%% IBIOColorDetectToolboxRegistryConfig
%
% Declare the toolboxes we need for the IBIOColorDetect project and
% write them into a JSON file.  This will let us use the ToolboxToolbox to
% deliver unto us the perfect runtime environment for this project.
%
% 2016 benjamin.heasly@gmail.com

% Clear
clear;

%% Declare some toolboxes we want.
config = [ ...   
    tbToolboxRecord( ...
    'type', 'git', ...
    'name', 'isetbio', ...
    'url', 'https://github.com:isetbio/isetbio.git'), ...
    tbToolboxRecord( ...
    'type', 'git', ...
    'name', 'UnitTestToolbox', ...
    'url', 'https://github.com:isetbio/UnitTestToolbox.git'), ...   
    tbToolboxRecord( ...
    'type', 'git', ...
    'name', 'RemoteDataToolbox', ...
    'url', 'https://github.com:isetbio/RemoteDataToolbox.git'), ...
    tbToolboxRecord( ...
    'type', 'git', ...
    'name', 'BrainardLabToolbox', ...
    'url', 'https://github.com:DavidBrainard/BrainardLabToolbox.git') ...
    % tbToolboxRecord( ...
    % type', 'git', ...
    % 'name', 'Psychtoolbox-3', ...
    % 'url', 'https://github.com/Psychtoolbox-3/Psychtoolbox-3.git', ...
    % 'subfolder','Psychtoolbox') ...
    ];

%% Write the config to a JSON file.
configPath = 'IBIOColorDetect.json';
tbWriteConfig(config, 'configPath', configPath);

%% Put these back in once tbtb is updated for subfolder order issue.
% tbToolboxRecord( ...
%     'type', 'installed', ...
%     'name', 'signal'), ...  
%     tbToolboxRecord( ...
%     'type', 'installed', ...
%     'name', 'stats'), ...  
%     tbToolboxRecord( ...
%     'type', 'installed', ...
%     'name', 'images'), ...    
%     tbToolboxRecord( ...
%     'type', 'installed', ...
%     'name', 'optim'), ...

