%% IBIOColorDetectToolboxRegistryConfig
%
% Declare the toolboxes we need for the IBIOColorDetect project and
% write them into a JSON file.  This will let us use the ToolboxToolbox to
% deliver unto us the perfect runtime environment for this project.
%
% 2016 benjamin.heasly@gmail.com

% Clear
clear;

%% Declare some toolboxes we want.
config = [ ...  
    tbToolboxRecord( ...
    'type', 'installed', ...
    'name', 'signal'), ...  
    tbToolboxRecord( ...
    'type', 'installed', ...
    'name', 'stats'), ...  
    tbToolboxRecord( ...
    'type', 'installed', ...
    'name', 'images'), ...    
    tbToolboxRecord( ...
    'type', 'installed', ...
    'name', 'optim'), ...   
    tbToolboxRecord( ...
    'type', 'installed', ...
    'name', 'robotics'), ...
    tbToolboxRecord( ...
    'type', 'git', ...
    'name', 'isetbio', ...
    'url', 'https://github.com:isetbio/isetbio.git'), ...
    tbToolboxRecord( ...
    'type', 'git', ...
    'name', 'UnitTestToolbox', ...
    'url', 'https://github.com:isetbio/UnitTestToolbox.git'), ...   
    tbToolboxRecord( ...
    'type', 'git', ...
    'name', 'RemoteDataToolbox', ...
    'url', 'https://github.com:isetbio/RemoteDataToolbox.git'), ...
    tbToolboxRecord( ...
    'type', 'git', ...
    'name', 'BrainardLabToolbox', ...
    'url', 'https://github.com:DavidBrainard/BrainardLabToolbox.git'), ...
    tbToolboxRecord( ...
    'name','Palemedes_1.8', ...
    'type','webget', ...
    'update','never', ...
    'url','http://palamedestoolbox.org/sitebuildercontent/sitebuilderfiles/palamedes1_8_2.zip') ...
    % tbToolboxRecord( ...
    % type', 'git', ...
    % 'name', 'Psychtoolbox-3', ...
    % 'url', 'https://github.com/Psychtoolbox-3/Psychtoolbox-3.git', ...
    % 'subfolder','Psychtoolbox') ...
    ];

%% Write the config to a JSON file.
configPath = 'IBIOColorDetect.json';
tbWriteConfig(config, 'configPath', configPath);


